version: '3.9'

services:

  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3316:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      web_segment:
        ipv4_address: 172.10.0.4
  app:
    container_name: html_css_try
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/var/www
    ports:
      - "3015:3000"
    depends_on:
      - db
    networks:
      web_segment:
        ipv4_address: 172.10.0.2

  # gw:
  #   image: nginx
  #   container_name: capo_kimura_gw
  #   ports:
  #   - 83:80
  #   volumes:
  #   - .:/var/www
  #   - ./docker/gw/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #   - app
  #   networks:
  #     web_segment:
  #       ipv4_address: 172.10.0.3

  # db:
  #   build:
  #     context: .
  #     dockerfile: docker/mysql/Dockerfile
  #   volumes:
  #     - ./docker/mysql/db:/docker-entrypoint-initdb.d
  #     - db-store:/var/lib/mysql
  #     - ./logs:/var/log/mysql
  #     - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #   ports:
  #     - "33306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: administrator
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: capo_kimura
  #     TZ: "Asia/Tokyo"
  #   networks:
  #     web_segment:
  #       ipv4_address: 172.10.0.4

networks:
  web_segment:
    driver: bridge
    ipam:
      config:
      - subnet: 172.10.0.0/24

volumes:
  db-store:
