version: '3.9'

services:
  db:
    image: mysql:8.0
    environment: # コンテナで利用する環境変数の定義
      TZ: UTC
      PGTZ: UTC
      MYSQL_PASSWORD: $MYSQL_PASSWORD # ホストの.envファイルで設定した環境変数をコンテナに流す
    volumes:
      - ./api/tmp/db:/var/lib/mysql/data

  api:
    build:
      context: ./api  # build context の指定 Dockerfile の場所
      args:
        WORKDIR: $WORKDIR
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./api:/$WORKDIR
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
  front:
    build:
      context: ./front  # build context の指定 Dockerfile の場所
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api
